### ISSUE TITLE
Typing random text instead of digits/variables throws an error.

### ISSUE THREAD

**Issue by shaansubbaiah** [sugarlabs/calculate-activity#67]
Reproduce:
	Type random text (eg. sweetener) -> Hit Enter / Equals symbol (=)

Traceback:

```python
1592573782.228379 DEBUG Calculate: Result: RuntimeError("Variable 'sweetener' not defined", 0,
 5)
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 133, in <lambda>
    lambda w: self._parent.process()],
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 552, in process
    self.set_error_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 444, in set_err
or_equation
    self.set_last_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 439, in set_las
t_equation
    self.layout.last_eq.set_buffer(eqn.create_lasteq_textbuf())
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 219, in create_
lasteq_textbuf
    resstr = str(self.result)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 110, in __str__
    {'a': self.eqn[self._range[0] - 1: self._range[1] - 1],
TypeError: 'NoneType' object is not subscriptable
```

Tested on:
	Calculate 46, Sugar 0.117-3, Debian Bullseye/ unstable

**Comment by chimosky** [comment]
Also saw this in the logs when I tested for this
```
(sugar-activity3:2676): Gtk-WARNING **: 02:18:54.854: Don't know color 'Gdk.Color(red=65535, green=65535, blue=65535)'
```
**Steps to Reproduce**
* Assign a value to a variable, say `s=4`.
* Multiply that value by a number, say `2*s`.

**Comment by quozl** [comment]
Finding the cause of Gtk-WARNING is so much easier on other applications, by using [--g-fatal-warnings](https://developer.gnome.org/gtk3/stable/gtk-running.html).  I don't know why it doesn't work on Sugar activities, but making it work would be useful for everyone.

I've seen the message before.  It suggests a string is being passed as a colour, and the string came from casting of a Gdk.Color.

Calculate variables are analogous to calculator memories.

**Comment by quozl** [comment]
I agree, your steps to reproduce are one way to cause the _TypeError: 'NoneType' object is not subscriptable_ on _master_ branch, though the traceback is slightly different on line 110 of astparser.py.

I've used `pdb` and found the cause of the Gtk-WARNING is passing a Gdk.Color of `'white'` to `create_tag` thus;

```python
        if bright < 0.5:
            col = Gdk.color_parse('white')
        else:
            col = Gdk.color_parse('black')
        tagcolor = buf.create_tag(foreground=col)
```

Documentation for Gtk.TextBuffer.create_tag gives an example of using a string for the foreground colour, not a Gdk.Color.

The Gtk-WARNING is avoided by using this;
```python
        if bright < 0.5:
            col = white'
        else:
            col = 'black'
        tagcolor = buf.create_tag(foreground=col)
```

No change to the traceback.  Hope that helps.

**Comment by shaansubbaiah** [comment]
Turns out that `eqn` is never passed while raising `RuntimeError` in `astparser.py`
eg. `RuntimeError(msg, ofs, ofs + len(node.id))`

Therefore the error is raised in RuntimeError function while trying to print it in L110 
```python
msg = _("Error at %s, position: %s") % \
		(self.eqn[self._range[0] - 1: self._range[1] - 1],
		self._range[0])`
```

None of the functions raising RuntimeError have `eqn` as a parameter and `eqn` is not part of RuntimeError's constructor so I think the string being assigned to `msg` is wrong. Changing the message string to something that doesn't use `eqn` fixes it.

eg.
```diff
class RuntimeError(ParserError):

    """Class for error during executing."""

    def __init__(self, msg, start, eqn, end=None):
        ParserError.__init__(self, msg, start, eqn, end)

    def __str__(self):
-        msg = _("Error at %s, position: %s") % \
-              (self.eqn[self._range[0] - 1: self._range[1] - 1],
-              self._range[0])
+        msg = _('Error')
        if self._msg is not None and len(self._msg) > 0:
            msg += ": %s" % (self._msg)
        return msg
```

Typing 's' and clicking '='/enter
![image](https://user-images.githubusercontent.com/11163839/88298239-8a3a2200-cd1e-11ea-8f19-786e65b4257f.png)

Though I'm not sure if this is the correct way to go about it

**Comment by chimosky** [comment]
@shaansubbaiah said
> Turns out that eqn is never passed while raising RuntimeError in astparser.py
eg. RuntimeError(msg, ofs, ofs + len(node.id))

`RuntimeError` is raised four times in `astparser.py` and two of those four `eqn` isn't passed and is passed in the other two, an additional if statement checking if it was added or not also changes the traceback and does fix the issue opened.


@quozl said
> The Gtk-WARNING is avoided by using this;
```
        if bright < 0.5:
            col = white'
        else:
            col = 'black'
        tagcolor = buf.create_tag(foreground=col)
```

Yeah that fixes the Gtk-Warning.

Another issue that persists is after creating a variable, the variable seems to be lost as performing any operation on the variable throws an ```Error: Variable 'variable name' not defined```.

**Comment by shaansubbaiah** [comment]
@chimosky thanks for checking. 

You have mentioned that `eqn` is passed in 2 instances when RuntimeError is raised. That seems to be going over my head even after taking another look at the code. Could you please explain where `eqn` is being passed?

**Comment by chimosky** [comment]
@shaansubbaiah said
> You have mentioned that eqn is passed in 2 instances when RuntimeError is raised. That seems to be going over my head even after taking another look at the code. Could you please explain where eqn is being passed?

Lines 540 and 550.

**Comment by shaansubbaiah** [comment]
@chimosky thanks, I should have been more clearer, I didn't understand how `eqn` gets passed. At those lines, aren't only `msg`, `start` and `end` passed?

**Comment by quozl** [comment]
Look further back.  In 2012, https://github.com/sugarlabs/calculate-activity/commit/eb9d99a849d7b45fad771bdeb646280c40a0d101 looks unfinished or untested;

* eqn is added to ParserError and saved in an instance variable - **pass**,
* eqn is added to ParseError, and the parent class ParserError saves it in an instance variable, and ParseError uses it in assembling msg - **pass**,
* eqn is added to RuntimeError, but it is not passed to the parent class ParserError (a bug), and so ParseError uses a misplaced argument - **fail**.

Looks like a careful review needed.

**Comment by chimosky** [comment]
@shaansubbaiah said
> @chimosky thanks, I should have been more clearer, I didn't understand how eqn gets passed. At those lines, aren't only msg, start and end passed?

At line 540 `RuntimeError(msg, ofs, ofs + len(node.id))` means the third argument is `eqn`, at line 550 `RuntimeError(msg, ofs, ofs + len(node.value))` means the third argument is `eqn`.

I agree with @quozl's observations above.

**Comment by quozl** [comment]
Also occurs on _python2_ branch.
