### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/calculate-activity#71]
Latest release seems to be v46 (if I understand correctly that v46.2 is intended for Python2 only) and was released more than a year a go.

Seems several nice improvement has been added to the master branch since then - please consider issuing a release - preferably quite soon, so it [has a chance of getting included with the upcoming Debian release](https://release.debian.org/bullseye/freeze_policy.html#summary)

**Comment by quozl** [comment]
Good idea, looking into that now.

**Comment by jonassmedegaard** [comment]
excellent :-)

**Comment by quozl** [comment]
https://download.sugarlabs.org/sources/sucrose/fructose/Calculate/Calculate-47.tar.bz2

**Comment by quozl** [comment]
Just being super curious, what's the cause of the delay between;
* the mail From: Debian FTP Masters <ftpmaster@ftp-master.debian.org> To: Debian Sugar Team <pkg-sugar-devel@lists.alioth.debian.org> with Subject: [Pkg-sugar-devel] sugar-calculate-activity_47-1_source.changes ACCEPTED into unstable

and

* the new version appearing in https://packages.debian.org/search?keywords=sugar-calculate-activity
* the new version in http://ftp.us.debian.org/debian/pool/main/s/sugar-calculate-activity/

**Comment by jonassmedegaard** [comment]
Quoting James Cameron (2021-02-02 23:15:00)
> Just being super curious, what's the cause of the delay between;
> * the mail From: Debian FTP Masters <ftpmaster@ftp-master.debian.org> To: Debian Sugar Team <pkg-sugar-devel@lists.alioth.debian.org> with Subject: [Pkg-sugar-devel] sugar-calculate-activity_47-1_source.changes ACCEPTED into unstable
> 
> and
> 
> * the new version appearing in https://packages.debian.org/search?keywords=sugar-calculate-activity
> * the new version in http://ftp.us.debian.org/debian/pool/main/s/sugar-calculate-activity/

No more than 6 hours.

When packages are accepted into Debian, they enter the "incoming" queue - which can be tracked at https://incoming.debian.org/ - and each 6 hours a cron job refreshes the regular queues, moving pending packages from incoming to unstable, and from unstable to testing.

**Comment by quozl** [comment]
Thanks!
